# Generated by Django 2.2.7 on 2019-12-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191201_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='priv_key',
        ),
    ]
